# Basic
title: firestealers
subtitle: 交流技术，分享乐趣
welcome_message: 欢迎来到道火技术乐园
description: This is the default description which you can customize
creator: <a href="">jesse</a>

url:
host:
port: 8081

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 查看博客

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: 缺省, description: , url: 'http://example.com'}

# Pagination, use a a special gem named jekyll-paginate
gems: [jekyll-paginate]
paginate: 6
paginate_path: "page/:num/"

# Social
social:
    # weibo:
    github: firestealers
    twitter: firestealers
    # gplus: 
    mail: github@daohuo.com

# no need for now
# Google Analytics
# ga:
    # id: your_ga_id
    # host: your_host
